const SET_MULTIPLE_TODO_LISTS = 'SET_MULTIPLE_TODO_LISTS';
const SET_MULTIPLE_TODOS = 'SET_MULTIPLE_TODOS';
const REMOVE_TODO_LIST = 'REMOVE_TODO_LIST';
const SET_TODO_LIST = 'SET_TODO_LIST';
const REMOVE_TODO = 'REMOVE_TODO';
const SET_TODO = 'SET_TODO';

export default {
  SET_MULTIPLE_TODO_LISTS,
  SET_MULTIPLE_TODOS,
  REMOVE_TODO_LIST,
  SET_TODO_LIST,
  REMOVE_TODO,
  SET_TODO,
};
