const SET_MULTIPLE_TODO_LISTS = 'SET_MULTIPLE_TODO_LISTS';
const REMOVE_TODO_LIST = 'REMOVE_TODO_LIST';
const SET_TODO_LIST = 'SET_TODO_LIST';

export default {
  SET_MULTIPLE_TODO_LISTS,
  REMOVE_TODO_LIST,
  SET_TODO_LIST,
};
